theme: jekyll-theme-midnight
title: Emeth Jamison
profile_image: /Screenshots/profile_pic.jpg

exclude:
  - node_modules
  - "**/node_modules"
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock

